### ISSUE TITLE
Wii needs ciso support!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PhoenixInteractiveNL/emuControlCenter#14]
So far I love this tool can you please add ciso extension support?

**Comment by PhoenixInteractiveNL** [comment]
Hi,

Sure, for which platform is it? (or all CD based platforms?)

**Comment by PhoenixInteractiveNL** [comment]
Oh lol it’s in the subject, only Wii? Or are there more platforms that use ciso?

**Comment by P3rf3ctXZer0** [comment]
I am not sure. Maybe make it global XD @PhoenixInteractiveNL I found this https://www.reddit.com/r/emulation/comments/3g933n/guide_reduce_the_size_of_your_ps2_gc_wii_x360_ds/ a .ciso means Compressed ISO it gets rid of the blank spaces of an iso.

On a side note; bit defender keeps flagging your website forums. Why is that?

![ss](https://cloud.githubusercontent.com/assets/10351221/21472962/6d17a70a-cab7-11e6-99f9-a48f0dcc0bcc.PNG)

**Comment by PhoenixInteractiveNL** [comment]
Hi P3rf3ctXZer0,

CISO has been added for all CD-based platforms!, added in update 00634

Hmm about the forum i don't get any warnings on my virus scans, it's a clean install of phpBB (with no addons or modules) with transferred database, so i don't know why this happens...

**Comment by PhoenixInteractiveNL** [comment]
Oh about CISO.... there is also CSO for compressed ISO images, it seems emulators are just adding extensions here and there haha...

**Comment by P3rf3ctXZer0** [comment]
Thank you :)
