### ISSUE TITLE
Can't Sign up?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [PhoenixInteractiveNL/emuControlCenter#15]
I am trying to use the EEC services Kamelon Code for game info can you tell me how to sign up?

**Comment by PhoenixInteractiveNL** [comment]
Hi, It's all described in the forum, i guess you have to click any topic around, then you'll see ;-)

Ps. the ECC/ICC services are down for the moment, due to server troubles...

**Comment by PhoenixInteractiveNL** [comment]
Awaiting your mail ;-)
