### ISSUE TITLE
Replace Xpadder with more recent Freeware

### ISSUE THREAD

**Issue by PhoenixInteractiveNL** [PhoenixInteractiveNL/emuControlCenter#8]
The freeware version of Xpadder is too old, and crashes on windows 8 & 10, so time to update this...
- Free option to select an executable on startup (just like Daemontools)
- Ship WorldOfJoysticks with ECC (instead of XPadder)

**Comment by PhoenixInteractiveNL** [comment]
Added this feature in update 00626
- Removed Xpadder and Xpadder options, the freeware v5.3 crashes on Windows 8/10.
- New Option to select a external Joystick emulator yourself now.
- Shipping WorldOfJoysticks v1.57 standard edition (worldofjoysticks.com) with ECC.

Enjoy!

**Comment by SixWingedFreak** [comment]
I own Xpadder, and have added it back into ECC. Using the /M switch (launch minimized and appear only in the taskbar tray) with Xpadder causes it to open and immediately close in a split second. I added the /M by adding it in general.ini:

`joyemulator_exe = "ecc-core\thirdparty\xpadder\Xpadder.exe /M"`

If I don't use /M it will launch fine but not minimized out of the way of course, which I prefer so it appears seamless. Using ECC 1.22 build:01 (2016.12.23) upd:00636.

Not sure how you could fix this, I have not looked at any of the code. Maybe under Configuration, where you choose a Joystick emulator, add an "Extra arguments" input box...? Maybe that's all that's needed?

**Comment by SixWingedFreak** [comment]
As a workaround, now I'm going to need to make a batch file to launch xpadder.exe with the /M switch, and then launch ecc.exe. Only problem with batch is xpadder won't close when ecc exits. On the other hand, I could write a simple AutoIt script... but that also wastes a tiny bit of CPU constantly checking for ecc.exe to finish (around 1-2% from initial testing)

**Comment by PhoenixInteractiveNL** [comment]
Hi SixWingedFreak,

I've found the issue and will look for a fix.

The problem is that we want to find the .exe, and therefore break the full path in pieces,
in ecc.au3:

`Global $ecc_external_JoyEmulator_temp =	_PathSplit($ecc_external_JoyEmulator, $sDrive, $sDir, $sFileName, $sExtension)`

`Global $ecc_external_JoyEmulator_exe =	$ecc_external_JoyEmulator_temp[3] & $ecc_external_JoyEmulator_temp[4]`

In this case there is no room for extra commands such as /M, so i will change the piece of code to also look for commandline parameters when using joystick emulators/programs.

Stay tuned!

**Comment by PhoenixInteractiveNL** [comment]
I will add a feature to enter parameters!

Stay tuned!

**Comment by PhoenixInteractiveNL** [comment]
WIP!
![ecc parameter option](https://cloud.githubusercontent.com/assets/20921263/22265350/04156ff8-e27c-11e6-98c3-d9e71a219125.png)

**Comment by PhoenixInteractiveNL** [comment]
Hi SixWingedFreak,

Has been added in UPDATE 00637, please try it out!

**Comment by SixWingedFreak** [comment]
Got update 00637. Xpadder launches on startup, but the Commandline parameter does not work. I tried 
`/M`
`\M`
`M`
But they all result in it launching normally, doesn't seem to be taking the parameter into effect.
Also tried various combinations in the ini

**Comment by PhoenixInteractiveNL** [comment]
To bad i cannot test it though..., but i have an idea....i will look into it!

**Comment by PhoenixInteractiveNL** [comment]
Hi,

Well i've tested it with a program wich had a simple scriptline:

Msgbox(64, "Commandline is:", "[" & $CmdLine[1] & "]")

And the result when adding this EXE as "joystickemulator" is:
![ecc joy commandline](https://cloud.githubusercontent.com/assets/20921263/22520804/0df556e2-e8b6-11e6-8891-ebf2eda8d235.png)

So it seems to work....

And if you add the /M to the INI
ecc-user-configs\config\ecc_general.ini

.....
[USER_DATA]
joyemulator_param = "/M"
....

Does that work?

**Comment by PhoenixInteractiveNL** [comment]
Also, when i read here: http://forum.arcadecontrols.com/index.php?topic=140637.0
It very likely seems a XPadder issue, maybe you can contact the author?

**Comment by SixWingedFreak** [comment]
It's working fine, I found out what my problem was and I feel incredibly stupid. I was using an old version of Xpadder on accident, I forgot they changed their versioning scheme. Everything is working OK now and those recently added commandline parameters work as intended. Thanks Phoenix!

**Comment by PhoenixInteractiveNL** [comment]
No problem! Glad it works!

Closing...
